In [ ]:
import numpy as np


In [24]:
dizi=np.full((4,3),5),
dizi

(array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]),)

In [4]:
#Yeni bir numpy dizisi oluşturuyoruz.
np.array([1,2,3])

array([1, 2, 3])

In [6]:
#Oluşturduğumuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["Elma","Erik","İğde"])

In [14]:
dizi

array(['Elma', 'Erik', 'İğde'], dtype='<U4')

In [25]:
dizi=np.array([1,2,3])

In [26]:
dizi=np.array([1,2,3.14])

In [27]:
dizi.dtype #dizinin değişken türünü verir. numpy dizilerinde elemanların hepsi ayrı türdendir.

dtype('float64')

In [28]:
dizi=np.array([1,2,3.14], dtype=int)

In [29]:
#Bir boyutlu dizi oluşturma 
birboyut=np.array([1,2,3,4])
#iki boyutlu dizi oluşturma 
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [30]:
birboyut

array([1, 2, 3, 4])

In [31]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
np.zeros(7) #7 sıfırdan oluşan tek boyutlu dizi oluşturur.

array([0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((2,3),dtype=int)#* sıfırdan oluşan iki boyutlu int dizi oluşturur

array([[0, 0, 0],
       [0, 0, 0]])

In [34]:
np.ones(3)

array([1., 1., 1.])

In [35]:
np.full((4,3),5)#başlangıc,bitiş ve artış değerine göre dizi oluşturma

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [36]:
np.arange(2,22,5)#başlangıc,bitiş ve artış değerine göre dizi oluşturma

array([ 2,  7, 12, 17])

In [39]:
np.linspace(2,10,num=7)#başlangıc ve bitiş aralığında belirtilen miktarda eşit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [42]:
np.random.randint(0,10,5)#0-10 aralığında rastgele 5 sayıdan oluşan bir boyutlu dizi

array([0, 7, 1, 5, 7])

In [44]:
np.random.randint(0,10,(5,2))#0-10 aralığında 5*2 rastgele sayıdan oluşan 2 boyutlu bir dizi

array([[6, 0],
       [5, 3],
       [6, 5],
       [4, 6],
       [9, 5]])

In [49]:
#dizilerin eleman sayısını öğrenmek için shape komutu kullanılır
dizi=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
dizi.shape

(3, 4)

In [50]:
#ndim dizi boyutunu öğrenmek için kullanılır
dizi.ndim

2

In [51]:
#size dizideki toplam eleman sayısını gösterir
dizi.size

12

In [52]:
#itemsize her bir elemanın bayt cinsinde değerini verir
dizi.itemsize

4